commit_message: '[ci skip] Update translations (%language%)'
append_commit_message: false
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        az: az
        ckb: ckb
        kmr: kmr
        gl: gl
        sc: sc
        kab: kab
        hi: hi
        ml-IN: ml
        fa: fa
        nb: nb-rNO
        sv-SE: sv
        es-ES: es
        de: de
        ru: ru
        pl: pl
        ja: ja
        it: it
        fr: fr
        da: da
        nl: nl
        hu: hu
        cs: cs
        ko: ko
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        el: el
        'no': 'no'
        tr: tr
        ca: ca
        pt-PT: pt
        pt-BR: pt-rBR
        fil: fil
        uk: uk
        ar: ar
        fi: fi
        af: af
        he: iw
        ro: ro
        vi: vi
        bs: bs
        sr: sr
        sr-CS: sr-rRS
        bn: bn
        pa-IN: pa
        jv: jw
        mr: mr
        te: te
        ur-PK: ur
        id: in
        sk: sk
        kn: kn
        ta: ta
        sq: sq
        mk: mk
        si-LK: si
        eo: eo
        or: or
    translate_attributes: 0
